# docker-compose.yml para levantar backend y frontend juntos
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - apinetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - apinetwork

networks:
  apinetwork:
    driver: bridge